### ISSUE TITLE
[BUG] Restore-PnPRecycleBinItem: The Attempted operation is prohibited because it exceeds the list view threshhold

### ISSUE THREAD

**Issue by 365gitsupport** [pnp/powershell#1598]
Hi 

We are currently having a problem regarding recovering deleted files from the recyclebin and second stage recycle bin.

When we run the command: Get-PnPRecycleBinItem  -RowLimit 200000 | ?    {($_.DeletedDate -gt $date2 -and $_.DeletedDate -lt $date1)} | Restore-PnPRecycleBinItem  -Force -RowLimit 200000

We get the error 
![image](https://user-images.githubusercontent.com/98897437/152314649-4d903bb8-512b-4e7f-80ce-09c58c57a3a3.png)

We have been in contact with MS Support and they told us to restore them in a batch and that didn't help either, we got the same error code as before.

The amount of files we are restoring are around 160 000 files.

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

It is an issue

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

To be able to recover deleted files from the recyclebin and second stage recyclebin

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

We get the error The Attempted operation is prohibited because it exceeds the list view threshhold

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

Connect-PnPOnline -Url https://customer.sharepoint.com/ -UseWebLogin
$today = (Get-Date)
$date1 = $today.date.addDays(-77)
$date2 = $today.date.addDays(-81)
Get-PnPRecycleBinItem  -RowLimit 200000 | ?    {($_.DeletedDate -gt $date2 -and $_.DeletedDate -lt $date1)} | Restore-PnPRecycleBinItem  -Force -RowLimit 200000

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

![image](https://user-images.githubusercontent.com/98897437/152314378-ff2e116e-4305-429e-b670-8864ddf68b8e.png)

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Closed as fixed via #2472

**Comment by NoahL989** [comment]
This still appears to be an issue. I downloaded the nightly version of PnP.PowerShell, I'm currently running version 1.11.109, and the -RowLimit parameter still isn't working for Restore-PnPRecycleBinItem.

Error that I am seeing is still the same:
![image](https://user-images.githubusercontent.com/116316586/197070877-2d64d9d0-c8b1-464e-b8ab-92e967d3be67.png)

**Comment by VonGlitch** [comment]
This ain't fixed!   I have a site collection with 390k items that need restoring.   I can't even restore them individually with Restore-PnPRecycleBinItem.   All I get is "The attempted operation is prohibited because it exceeds the list view threshold."

One by one, batches of 200, -RowLimit or not, -Force or not ... same error.

I've tried PnP.PowerShell versions 1.10, 1.11, 1.12 and even the new 2.1.1 --- all of them broken!!

**Comment by tylamb1** [comment]
I am also having issues.  I have installed the latest version.  The code I am using is

$today = (Get-Date)
$restoreDateStart = $today.date.AddDays(-19)
$restoreDateEnd = $restoreDateStart.AddHours(23.99999)
$date_string = Get-Date -UFormat "%Y%m%d.%H%M%S"
$currentSet = Get-PnPRecycleBinItem | ? {($_.DeletedDate -gt $restoreDateStart) -and ($_.DeletedDate -lt $restoreDateEnd) -and ($_.DeletedByEmail -eq 'email@address.com')} | select -last 100
$currentSet | Export-Csv ".\robin.files.restore.$date_string.csv"
$currentSet | Restore-PnpRecycleBinItem -Force


I can export $currentSet and have 100 items in the file but I can not restore them.  I get the error in red text.

"Restore-PnPRecycleBinItem: The attempted operation is prohibited because it exceeds the list view threshold."

**Comment by ReedME** [comment]
I too am experiencing this same issue.

**Comment by MrRCG5** [comment]
It's not working for me either.
