### ISSUE TITLE
Set-PnPContext not switching the context!

### ISSUE THREAD

**Issue by omarmallat** [pnp/powershell#1729]
### Reporting an Issue or Missing Feature
Issue with using Set-PnPContext to switch between two connections

### Expected behavior 
as per the[ documentation example](https://pnp.github.io/powershell/cmdlets/Set-PnPContext.html), Set-PnPContext must switch to the context defined as parameter
```
Connect-PnPOnline -Url $siteAurl -Credentials $credentials
$ctx = Get-PnPContext
Get-PnPList # returns the lists from site specified with $siteAurl
Connect-PnPOnline -Url $siteBurl -Credentials $credentials
Get-PnPList # returns the lists from the site specified with $siteBurl
Set-PnPContext -Context $ctx # switch back to site A
Get-PnPList # returns the lists from site A
```

### Actual behavior 
Regardless of the context mentioned in the command parameter, the context remains as per the last connection made. the command Set-PnPContext is doing nothing

### Steps to reproduce behavior
```
Connect-PnPOnline -URL $SiteA_URL -Interactive
$ctxA=Get-PnPContext
$listA= Get-PnPList # show lists in site A

Connect-PnPOnline -URL $SiteB_URL -Interactive
$ctxB=Get-PnPContext
$listB= Get-PnPList # show lists in site B

$ctx=Get-PnPContext # return the context of the last connection made, for Site B
Set-PnPContext -Context $ctxA # Expected to set the context of the site A
$list= Get-PnPList # Still return the list from the site B, which is the last connection made
$ctx=Get-PnPContext # still return the context of Site B
```

### What is the version of the Cmdlet module you are running?
1.9.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
This has been fixed in the latest nightly builds

https://github.com/pnp/powershell/issues/1089

Please try with that and let us know :)

**Comment by gautamdsheth** [comment]
Hey closing this issue.

Please update to the latest 1.10 release which contains the fix for this issue :)

**Comment by omarmallat** [comment]
for the information, **problem still as is**, even after upgrading to 1.10

**Comment by gautamdsheth** [comment]
Please do a clean install

**Comment by gautamdsheth** [comment]
@omarmallat ,can you please do a clean install and remove the old version of the module and they try ?

**Comment by omarmallat** [comment]
I removed all the old versions, I installed the latest 1.10.0 and still having the same issue.

**Comment by damsleth** [comment]
The `Set-PnPContext` command seems to switch context correctly, but it gets overwritten when running e.g. `Get-PnPList`.  
Other commands also seem to be using the url from the _current connection_, instead of the _current context._, for example `Get-PnPField`, which returns `The object is used in the context different from the one associated with the object.`.

#### Steps to reproduce the context being overwritten by `Get-PnPList`

```
Connect-PnPOnline -URL $SiteA_URL -Interactive
$ctxA=Get-PnPContext
Connect-PnPOnline -URL $SiteB_URL -Interactive
$ctxB=Get-PnPContext

Set-PnPContext -Context $ctxA

Get-PnPContext # returns context for site A

Get-PnPSite # returns site A

Get-PnPList # returns lists from site B

Get-PnPSite # returns site B - the current context was switched by running get-pnplist
```

Running v1.10.24

**Comment by damsleth** [comment]
As a workaround, it's possible to (for now) use the deprecated `Web` parameter, like so
``` 
Connect-PnPOnline -URL $SiteA_URL -Interactive
$ctxA=Get-PnPContext

Connect-PnPOnline -URL $SiteB_URL -Interactive
$ctxB=Get-PnPContext

Set-PnPContext -Context $ctxA
$webA = Get-PnPWeb 

Get-PnPList -Web $webA # returns all lists from $webA, and doesn't change current PnPContext
``` 

The same workaround can also be used for e.g. `Get-PnPField`, `Get-PnPUser` and all commands doing `CurrentWeb.Context.Load` or `ClientContext.Load(CurrentWeb.[whatever])` in `ExecuteCmdlet`

**Comment by KoenZomers** [comment]
Having a look here to see if I can repro this. I've done some rework on the connection stuff. Perhaps this fixed this issue already as well. Let me try to reproduce this.

**Comment by heinrich-ulbricht** [comment]
I so hope that this is the solution for https://github.com/pnp/powershell/issues/1949

**Comment by Cadder** [comment]
This issue still exists in 1.11.0. See https://github.com/pnp/powershell/issues/2150
