### ISSUE TITLE
[BUG] Unable to associate site from another Geo location tenant with hub-site in main tenant 

### ISSUE THREAD

**Issue by vurtual1** [pnp/powershell#1911]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Run Add-PnPHubSiteAssociation and site becomes associated with hub site

### Actual behavior 
"Add-PnPHubSiteAssociation: File Not Found."

### Steps to reproduce behavior
Add-PnPHubSiteAssociation -Site "https://geotenant.sharepoint.com/sites/SomeSite" -HubSite "https://hometenant.sharepoint.com/sites/HubSite"

### What is the version of the Cmdlet module you are running?
1.10

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by praveenbattula** [comment]
You have closed other issue and also this one. But I don't see any update on either. I also face exact same issue

**Comment by veronicageek** [comment]
@praveenbattula - This issue is not closed

**Comment by gautamdsheth** [comment]
hi @vurtual1 , we have fixed this issue. It is available in nightly builds and the next major version when we release it.

It requires delegated permissions to work though due to API limitatins, just something you need to keep in mind.

**Comment by GetThisIs4** [comment]
Hello, this is still happening. We cannot associate a site to a HUB site from another geo location using this powershell cmdlet Add-pnpHubSiteAssociation. 
But it is working on the GUI. When will this be fixed?

**Comment by Jayeshgt** [comment]
Hi, this issue still persists, I just now verify with the Multi Geo tenant Add-PnPHubSiteAssociation throws an error  **_"The passed configuration 'https://xxxxxx.sharepoint.com/sites/HubSite does not exits"_** and When I try to get the Hub Site using Get-PnPHubSite -Identity https://xxxxx.sharepoint.com/sites/HubSite it throws exception **_"Proxy request for hubsite GetById failed with following error: The remote server returned an error: (401) Unauthorized."_** kindly let us know is it fixed? I have 1700+ sites where I have to associate hub site. I have tried with PowerShell version 5.1 and 7.4.5 and PnP Version 2.12.0. Appreciate your early help.

**Comment by Jayeshgt** [comment]
when we use delegate permission it works thank you

**Comment by vurtual1** [comment]
> when we use delegate permission it works thank you

It says in the fix "It requires delegated permissions to work though due to API limitatins, just something you need to keep in mind." I don't think a broader fix is coming at this point, due to that. 

I used the JoinHubSite REST API instead, 100,000 sites in 3 geos.
