### ISSUE TITLE
[BUG] Register-PnPAzureADApp - Bad Request error when attempting to register app.

### ISSUE THREAD

**Issue by JustinCLyon** [pnp/powershell#3316]
### Reporting an Issue or Missing Feature
When registering a PnPAzureADApp, An exception is returned concerning a non-nullable value being detected as null

`Register-PnPAzureADApp -ApplicationName TestApp -Tenant yourtenant.onmicrosoft.com -Store CurrentUser -Username "yourname@domain.com" -Password (Read-Host -AsSecureString -Prompt "Enter Password")`

### Expected behavior 
The cmdlet continues to the consent flow and after being accepted, a certificate is issued.

### Actual behavior 
The Request returns with the following error:
`Register-PnPAzureADApp: {"error":{"code":"Request_BadRequest","message":"A null value was found with the expected type 'Edm.String[Nullable=False]'. The expected type 'Edm.String[Nullable=False]' does not allow null values.","innerError":{"date":"2023-07-31T16:01:04","request-id":"8914a89d-8831-42fb-a596-591f38843517","client-request-id":"8914a89d-8831-42fb-a596-591f38843517"}}}`

### Steps to reproduce behavior
Following guide [here](https://www.c-sharpcorner.com/article/certificate-based-authentication-to-connect-to-sharepoint-online-sites/), simply the first step. Account being used it a tenant administrator, no MFA.

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
PnP PowerShell 2.2.0
### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @JustinCLyon , the issue has been fixed in the latest nightly builds.
Please use the nightly builds for this.

https://pnp.github.io/powershell/articles/installation.html#nightly-build

**Comment by ajcaterino** [comment]
I installed the nightly build and it is still a problem.

`Register-PnPAzureADApp: {"error":{"code":"Request_BadRequest","message":"A null value was found with the expected type 'Edm.String[Nullable=False]'. The expected type 'Edm.String[Nullable=False]' does not allow null values.","innerError":{"date":"2023-08-01T15:25:04","request-id":"79dd654b-9967-4410-aca1-2caab424373a","client-request-id":"79dd654b-9967-4410-aca1-2caab424373a"}}}`

**Comment by ajcaterino** [comment]
I did get it to work. I uninstalled the main 2.2.0 version and installed the nightly build by itself.
