### ISSUE TITLE
[BUG] Connect-PnPOnline: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.50.0.0

### ISSUE THREAD

**Issue by gitulm** [pnp/powershell#3408]
I use Powershell 7.3.6 with Visual Studio Code 1.82.1 and Powershell Extension v2023.6.0 and PnP.Powershell 1.12.0 on Windows 10

When I connect to Connect-PnPOnline -Url https://xxx.sharepoint.com I get the following error:

Connect-PnPOnline: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.50.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. Could not find or load a specific file. (0x80131621)

When I do this in Powershell 7.3.6 everything is o.k. 

Operation System:
Windows

**Comment by gautamdsheth** [comment]
Hi , this issue has been fixed in the latest nightly builds.

Please check it out.

**Comment by gitulm** [comment]
It was solved in the last nightly builds, but today the problem also occurs in the nightly build:

Version: 1.83.0-insider (user setup)
Commit: 10765021158cf51eaf6785361598e1668f53e06e
Date: 2023-09-18T15:06:20.425Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by robertcaretta** [comment]
Having same issue with PnP 2.2.0, PS 7.3, VS Code, extension, etc.  So issue is not fixed?

**Comment by gitulm** [comment]
This issue is currently reoccurring in VSC 1.83.1. It doesn't occur in the nightly build of VSC. Why is this constantly changing?

**Comment by jaysonhinton** [comment]
I am getting the same error when with PS 7.3.8 and PnP 2.2 if I have other modules loaded. Specifically Microsoft.Graph module.
