### ISSUE TITLE
[FEATURE] Fully support Enable File Requests in SharePoint or OneDrive

### ISSUE THREAD

**Issue by nikki-c** [pnp/powershell#3554]
**Is your feature request related to a problem? Please describe.**
Limited functionality

**Describe the solution you'd like**
I can use PnP to set the Request files at a tenant level for sites and OneDrive, e.g.  Set-PnPTenant -CoreRequestFIlesLinkEnabled $True -CoreRequestFilesLinkExpirationInDays 14 -OneDriveRequestFIlesLinkEnabled $True -OneDriveRequestFilesLinkExpirationInDays 7
and also at the site level, e.g. Set-PnPSite -Identity $SiteURL -RequestFIlesLinkEnabled $True -RequestFilesLinkExpirationInDays 30

However, Get-PnPTenant and Get-PnPSite do not return the current values, so I must revert to SharePoint Online PowerShell.

**Describe alternatives you've considered**
You can use SharePoint Online PowerShell as described https://learn.microsoft.com/en-us/sharepoint/enable-file-requests
Get-SPOTenant | Format-List CoreRequestFIlesLinkEnabled, CoreRequestFilesLinkExpirationInDays, OneDriveRequestFIlesLinkEnabled, OneDriveRequestFilesLinkExpirationInDays
Get-SPOSite -Identity $SiteURL | Select-object url, RequestFIlesLinkEnabled, RequestFilesLinkExpirationInDays 

**Additional context**
Screenshot of sunning Get-PnPSite and Get-SPO site 
![image](https://github.com/pnp/powershell/assets/69439002/ca9e7471-c590-4a43-a13c-537d76cb25c5)

**Comment by KoenZomers** [comment]
Correct, these are missing. Adding them now.

**Comment by gautamdsheth** [comment]
hi @nikki-c , has been fixed. Will be available in tomorrow's nightly builds as well as the next major version when we release it.

**Comment by spigaz** [comment]
I have just tried with nightly build that I installed using
Install-Module PnP.PowerShell -AllowPrerelease

And it still doesn't show the option in Get-PnPTenant, although I got confirmation that its working now for sharepoint users.

Thanks!

**Comment by KoenZomers** [comment]
@spigaz Works here. What is this returning for you?

<img width="750" alt="image" src="https://github.com/pnp/powershell/assets/5940670/d225cb8d-2376-456f-a9bc-1e958ee1652b">

**Comment by spigaz** [comment]
<img width="532" alt="image" src="https://github.com/pnp/powershell/assets/849936/587bd111-5e5a-4e5f-813a-78796f42a4c5">

I don't know, something went wrong when I installed the Prerelease? I had to use -Force

**Comment by spigaz** [comment]
I existed the powershell and then tried again and it works now.
<img width="536" alt="image" src="https://github.com/pnp/powershell/assets/849936/0439be61-1593-4196-a754-5fa79d166fe3">

**Comment by KoenZomers** [comment]
Must be that you already invoked PnP PowerShell in that PowerShell screen before you updated. In that case, it keeps it in memory.

**Comment by spigaz** [comment]
It makes sense. Thanks!
