### ISSUE TITLE
[BUG] Export-PnPTermGroupToXml and Import-PnPTermGroupFromXml not working

### ISSUE THREAD

**Issue by Ron-Rohlfs** [pnp/powershell#3807]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Reporting an issue
Import-PnPTermGroupFromXml: Template is not valid
Other issues like this (_e.g._, https://github.com/pnp/PnP-PowerShell/issues/2303,  https://github.com/pnp/PnP-Sites-Core/issues/2794) are out-of-date or closed.

### Expected behavior 
The .xml file created by Export-PnPTermGroupToXml from the source tenant should be usable by Import-PnPTermGroupFromXml to the destination tenant.

### Actual behavior 
Export-PnPTermGroupToXml works as expected.
Import-PnPTermGroupFromXml gives "Template is not valid" error.

### Steps to reproduce behavior
$xmlFilePath = "C:\temp\TermStore\TermGroup.xml";

$uid = "globaladmin@sourcetenant.onmicrosoft.com"; $msg = "Enter pwd";
$cred = Get-Credential -UserName $uid -Message $msg;
$siteUrl = "https://********-admin.sharepoint.com/";
$tenantUrl = "https://********-admin.sharepoint.com/";
$sourceTenantConnection = Connect-PnPOnline -Url $siteUrl -TenantAdminUrl $tenantUrl -Credentials $cred -ReturnConnection:$true;

$termgroup = Get-PnPTermGroup -Connection $sourceTenantConnection -Identity "Meeting Rooms";
$termgroup | Export-PnPTermGroupToXml -Connection $sourceTenantConnection -Out $xmlFilePath;

$uid = "globaladmin@targettenant.onmicrosoft.com"; $msg = "Enter pwd";
$cred = Get-Credential -UserName $uid -Message $msg;
$siteUrl = "https://********-admin.sharepoint.com/";
$tenantUrl = "https://********-admin.sharepoint.com/";
$targetTenantConnection = Connect-PnPOnline -Url $siteUrl -TenantAdminUrl $tenantUrl -Credentials $cred -ReturnConnection:$true;

Import-PnPTermGroupFromXml -Connection $targetTenantConnection -Path $xmlFilePath;

### What is the version of the Cmdlet module you are running?
Version 2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows 10
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by NoralK** [comment]
@Ron-Rohlfs - PnP.PowerShell is upto v2.4.0.  In v2.3.0 `Export-PnPTermGroupToXml` https://github.com/pnp/powershell/pull/3256 was fixed.

**Comment by Ron-Rohlfs** [comment]
Thanks @NoralK ! v2.4.0 worked like a champ.

**Comment by thunderstorm654** [comment]
I am still getting this error on version 2.4.0, simple export of term group and XML and immediately try to import and always get the error 'Data at the root level is invalid. Line 1, position 1.'.
