### ISSUE TITLE
[BUG] Set-PnPPageTextPart and Set-PnPPageWebParts cmdlets are appending extra banner section along with existing banner in the updated page after updating the new text in the Text OOB component as well as in other Components

### ISSUE THREAD

**Issue by kssai94** [pnp/powershell#4313]
### Reporting an Issue

While setting new text value to the Text Out of the box webpart(using Set-PnPPageTextPart cmdlet) and also while updating the webpart properties back to other oob/custom webpart (using Set-PnPPageWebPart cmdlet) programmatically through powershell, Additional banner is getting appended along with the existing banner in the updated page.

### Expected behavior 
Set-PnPPageTextPart and Set-PnPPageWebPart cmdlets should set the new data only on the text out of the box webpart and custom/oob webpart respectively. It should not append any new banner in the updated page after setting the text/webpart properties.

### Actual behavior 
Set-PnPPageTextPart and Set-PnPPageWebPart cmdlets are appending new banner after setting the new text or webpart properties for text oob/custom webparts which is weird and strange.
Ideally It should not have duplicate banner in the updated page after setting new text content in webpart.
It should update only the new text content in the oob/custom webpart.

### Steps to reproduce behavior

#Note: Please create a new Modern Page and add text OOB component and add some content in it and publish the page.
Then utilize the same page name below. Please use other parameters like credentials if you are unable to connect to Sharepoint Online.

Code Snippet
===============

$siteUrl = "https://resources.deloitte.com/sites/<Anysite>"
$appId = ""
$appSecret = ""

# Connect to SharePoint Online
$global:pnpConnection = Connect-PnPOnline -Url "$($siteUrl)" -ClientId $appId -ClientSecret $appSecret -WarningAction Ignore ReturnConnection

$pageName = "<Any new page where a simple Text OOB webpart is added in a new section after the default banner section , Eg : Page-Text-Webpart.aspx>" 

try {

    #Main Function
    $page = Get-PnPPage -Identity "$($pageName)" -Connection $global:pnpConnection

    foreach ($control in $page.Controls) {

        try {
            
            #region Set Webpart Properties according to the language    
            
            $updatedText = "Iam fine"
            #$updatedText = "How are you?"
            #$updatedText = "Hope your family is well"
            # ConvertTo-Html -InputObject $control | Out-Null
            # Write-Host $($control.ControlType)
            if($control.Type.ToString().IndexOf("PageText") -ge 0){
                $control.ToHtml($control.ControlType) | Out-Null
                Set-PnPPageTextPart -Page $pageName -InstanceId $control.InstanceId -Text $updatedText -Connection $global:pnpConnection
            }
            elseif ($control.WebPartId -eq "05fea897-2a15-4086-9c28-26c5586588aa"){
                $control.ToHtml($control.ControlType) | Out-Null
                Set-PnPPageWebPart -Page $pageName -Identity $control.InstanceId -PropertiesJson $control.JsonWebPartData -Connection $global:pnpConnection
            }

        }
        catch {
            Write-Host $_
            $pageConversionLogCount.Status = "Error"
        }
    }

}
catch {
    Write-Host "[ERROR]: $_ at $($_.InvocationInfo.ScriptLineNumber) LineNumber In Main Function (Triggering Point)"
    # log -content "[ERROR]: $_ at $($_.InvocationInfo.ScriptLineNumber) LineNumber In Main Function (Triggering Point)" -path $logParentFilePath
    $parentLogCount.Status = "Error"
}

$global:pnpConnection = $null 

Page before updating new text in Text OOB webpart :
<img width="347" alt="image" src="https://github.com/user-attachments/assets/5382bb17-77d6-4c15-aa50-eceff96534d1">

Page after updating new text in Text OOB webpart :
<img width="302" alt="image" src="https://github.com/user-attachments/assets/2602b542-1076-4623-b1a8-6fe923ea025f">

### What is the version of the Cmdlet module you are running?

ModuleType Version  Pre-release            Name                               PSEdition                         

Manifest        2.1.1                                 PnP.PowerShell                      Desk

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows

##Powershell Version - 7.4.5
##node version - v16.17.1
##npm version - 8.15.0

Please suggest a resolution for this issue.

Thank you,
Sreekrishna Sai

**Comment by jethva-aakash** [comment]
I am facing the same issue. For me, it happens when the Page has a Vertical Section. If I remove this Vertical section, it does not add the duplicate Page Title.

**Comment by kssai94** [comment]
Hi Aakash,

Thanks for the acknowledgement, Even i'm also able to reproduce this issue only in the vertical section.

But after creating a new copy page of this existing page for translating language and try to set newly translated text back to webpart, I'm getting below error :

"You cannot host text controls inside a one column full width section, only an image web part or hero web part are allowed".

As part of latest developments, Microsoft is allowing us to delete the default full width section with banner and also it is allowing us to add banner webpart inside Full width section.

Please Correct me if i'm wrong.

Also It is giving above error for all webparts including OOB ones in the page when we use cmdlets with set verb. Thus i'm unable to update newly translated text in the newly created copy pages.

This is the API i'm using to create page : $url = "$($siteUrl)/_api/sitepages/pages($pageId)/translations/create"
$response = Invoke-PnPSPRestMethod -Url $url -Method Post -Content $body -ContentType "application/json;odata=verbose" -Raw -Connection $global:pnpConnection | ConvertFrom-Json

Can anyone from PnP Team check this issue and resolve asap.

**Comment by kssai94** [comment]
> I am facing the same issue. For me, it happens when the Page has a Vertical Section. If I remove this Vertical section, it does not add the duplicate Page Title.

Hi Aakash, Could you please check once again as issue is again reproducing, Thanks

**Comment by cibun** [comment]
new version of the PowerShell
 2.12.0 has fixed the issue.

**Comment by jethva-aakash** [comment]
We already tried V2.12.0 earlier but still the same. Following are some screenshots of the same,

![01-NewPage](https://github.com/user-attachments/assets/2341bcb2-8420-40e5-b8a7-1411b29799d1)

![02-Update Text](https://github.com/user-attachments/assets/c28e8539-8774-4a4e-a3f2-918445741938)

![03-Duplicate Header](https://github.com/user-attachments/assets/c48cf711-a33f-4bce-bfbc-32b3fc1ef270)

**Comment by gautamdsheth** [comment]
Hello, can you please try again with latest nightly builds and let us know ? Looks like it has been fixed .

**Comment by jethva-aakash** [comment]
I tried with 2.12.19-nightly but still the same.

**Comment by tyagia10** [comment]
I tried even with 2.12.20-nightly but still facing the issue.

**Comment by jethva-aakash** [comment]
@gautamdsheth It seems to me like the issue is connected with the recent changes by Microsoft related to Page content handling. Could it be that the CSOM library does not support the latest M365 version yet? Is there any solution or workaround that you can suggest?

**Comment by tarjeieo** [comment]
I'm seeing this issue with pages with vertical sections when I just update/publish them, without adding or modifying the page itself. The page will have it's banner-section "reset" and an extra banner web part is added.

Repro with 2.12.0:
```
$CurrentItem = Get-PnPListItem -List SitePages -Id 69
Set-PnPListItem -List SitePages -Identity $CurrentItem.Id -Values @{"Modified" = $NowValue} -UpdateType UpdateOverwriteVersion
Set-PnPPage -Identity $CurrentItem.FieldValues.FileLeafRef -Publish
```

This is how it looks after:
![image](https://github.com/user-attachments/assets/be3bf511-0117-4fa8-ba56-0d5c429b5b9a)

**Comment by SteenMolberg** [comment]
I ran into this when creating automatic updating of page with a script based of PNP Powershell. I don't think the bug is in PNP Powershell, but when working with the page, like replacing a webpart, an additional header is inserted into "LayoutWebpartsContent" field. It looks like it is related to a vertical section on the page.

You can reset the "LayoutWebpartsContent" with the following script:

```powershell
Set-PnPListItem -List "Site Pages" -Identity [insert here id of page item] -Values @{ LayoutWebpartsContent = "<div></div>" } -UpdateType SystemUpdate
```

**Comment by armourking** [comment]
> You can reset the "LayoutWebpartsContent" with the following script:
> 
> ```powershell
> Set-PnPListItem -List "Site Pages" -Identity [insert here id of page item] -Values @{ LayoutWebpartsContent = "<div></div>" } -UpdateType SystemUpdate
> ```
This works great, thank you!

**Comment by Galmiar57** [comment]
# Duplicate banner issue on pages with a vertical section (**with PnP 2.12.0**)

## Bug Description
This issue occurs when creating a page with a banner (full-width section) and a vertical section. After saving the page using `Get-PnPPage`, the banner is duplicated. Subsequent attempts to fix the issue temporarily (e.g., using `Set-PnPListItem`) result in a loss of the full-width format for the banner, and the issue reoccurs after each update.

## Steps to Reproduce
1. Create a page with the following structure:
   - A banner in a full-width section.
   - A vertical section.
2. Save any update on this page using the `Get-PnPPage` command.
3. Navigate to the page in a browser and observe that the banner is duplicated.
4. Apply the workaround:
   - Use the command `Set-PnPListItem -Identity <PageId> -Values @{"LayoutWebpartsContent"="<div></div>"}`.
5. Navigate to the page again:
   - The duplicate banner is resolved, but the **full-width format for the banner is lost.**
6. Save the page again using `Get-PnPPage`.
7. Navigate to the page and observe that the duplicate banner issue reoccurs.

## Expected Behavior
- The page should maintain the full-width section layout for the banner.
- The banner should not be duplicated after saving or updating the page.

## Actual Behavior
- The banner is duplicated after the first save using `Get-PnPPage`.
- Applying the workaround removes the duplicate banner but breaks the full-width layout.
- The issue reoccurs after each save or update.

## Screenshots
![step1](https://github.com/user-attachments/assets/7c317c37-3b10-4fdc-8c8e-8e2c010de5cf)
![step2](https://github.com/user-attachments/assets/eb147613-9ab9-488a-bda5-4efcc38df627)
![step3](https://github.com/user-attachments/assets/99bc84ec-78c2-49af-80c4-39e784b65698)
![step4](https://github.com/user-attachments/assets/cb260c6b-7ecc-4cc0-a3ee-80c6a58f4835)
![step5](https://github.com/user-attachments/assets/c41559a5-ee8c-4394-affd-7b93182927ff)
![step6](https://github.com/user-attachments/assets/5fc25b7b-5cc4-4b1f-9f43-2b07fc5c139f)
![step7](https://github.com/user-attachments/assets/40eab4a5-b1e7-4b33-bd5a-03e6eee9cfae)

## Additional Context
This issue makes it difficult to maintain the desired layout when pages include both a full-width section and a vertical section.

**Comment by VPO-jhenderson** [comment]
Issue also exists when using Export-PnPPage and then Invoke-PnPSiteTemplate. 
Exact same issue ad described above.

As described in this issue, deleting the Vertical Section allows the headers to be displayed correctly. 

Source:

![Image](https://github.com/user-attachments/assets/01f7193d-9a54-4fdc-aa53-67d3661a713b)

Target:

![Image](https://github.com/user-attachments/assets/9c024d89-fb68-4fb8-a4ce-4c50b2628c86)

This is part of a larger PS code base we use internally. Can confirm that this code worked flawlessly a few months ago. 

As described in this issue, deleting the Vertical Section allows the headers to be displayed correctly. 

Curiously, when I first attempted to recreate the issue in a controlled environment, the code ran as expected. However, after I modified the source page (In my case, I added a spacer to the vertical section) the page would not longer copy successfully. My first thought was that when you modify a page that existed pre-whatever MSFT changed , it works as expected. But anything modified after that time it did not. 

For context, this is the code I use:
function exportPages {
    param(
        $pageNames,
        $exportDirectory
    )

    if ($exportDirectory.endsWith('\')) {
        $exportDirectory = $exportDirectory.substring(0, $exportDirectory.length - 1)
    }

    if (!(test-path $exportDirectory)) {
        new-item -Path $exportDirectory -ItemType Directory | out-null
    }

    foreach ($pageName in $pageNames) {
        if(!$pageName.endswith('.aspx')){
            write-host "'$pagename' is not a full valid Sharepoint page name. Skipping..." -f yellow
            continue
        }
        try {
            Write-host "Exporting '$pageName' to $exportDirectory..." -f Cyan -NoNewline
            **Export-PnPPage -Force -Identity $PageName -Out "$exportDirectory\$pageName" | out-null**
            write-host "Success" -f green
        }
        Catch {
           write-host "Could not export '$pagename'. It likely does not exist" -f yellow
        }# try catch export pnp page
    }# foreach page
} #functin ExportPages

function deployPages {
    Param(
        $PagesDirectory
    )
    $currentSiteName = (get-pnpweb).Title

    $pages = (get-item "$PagesDirectory\*").Name
    $backupDirectory = ".\PageBackups\$(gettenantURLSeg)\$($currentSiteName)_$(get-date -format "yyyyMMddHHmm")"
    Write-host "Backing up '$currentSiteName' pages to $backupDirectory ..." -f blue
    exportPages -pageNames $pages -exportDirectory $backupDirectory
    
    foreach ($page in $Pages) {
        if(!$page.endswith('.aspx')){
            write-host "'$page' is not a full valid Sharepoint page name. Skipping..." -f yellow
            continue
        }
        Try {
            write-host "Uploading '$page' to $currentSiteName..." -f cyan -NoNewline
            **Invoke-PnPSiteTemplate -Path "$PagesDirectory\$page" | out-null**
            Write-host "Success" -f green
        }
        Catch {
            errmsg "Failed to upload '$page' to $currentSiteName $($_.Exception.Message)"
        } #try Catch Uplaod page
    }# foreach page
}# function deployPages

![Image](https://github.com/user-attachments/assets/bf29e5b1-2158-4f00-8115-414990cfde47)

**Comment by devtica** [comment]
When Set-PnPPageWebPart will be fixed for page with full width banner and vertical section?

**Comment by tmohrlueder** [comment]
We face the same issue and I did a little debugging with the dev branch of PnP.Core (commit ae8cf11):

The bug itself is still there, although different than what we are experiencing.

We get an empty header, with the original header seemingly being duplicated and moved to the first section. We are using the PnP.Framework NuGet package version 1.17.0 (.NET/C#).

With the dev branch of PnP.Core the header just moves into the first section (so the page is left without a header at all), nothing is duplicated.

However, this is fixed by setting the sectionFactor to 0 in the header control. For whatever reason it is being set to 12 by PnP.Core (it's a null-coalesce default value of ColumnFactor in CanvasColumn which is used as the value for SectionFactor in CanvasData).

Maybe this helps? Other than that the behavior looked fine (in my admittedly brief test).

Additional info: I created a page via UI using the Blank template on a fresh Communication site, added the vertical section and clicked Publish. I then downloaded the .aspx file using Get-PnPFile, modified it in VSCode (replacing only 12 with 0 of the sectionFactor property in the first data-sp-controldata block) and re-uploaded it via Add-PnPFile (after enabling script files with Set-SPOsite ... -DenyAddAndCustomizePages 0).

**Comment by balle3201** [comment]
> I'm seeing this issue with pages with vertical sections when I just update/publish them, without adding or modifying the page itself. The page will have it's banner-section "reset" and an extra banner web part is added.
> 
> Repro with 2.12.0:
> 
> ```
> $CurrentItem = Get-PnPListItem -List SitePages -Id 69
> Set-PnPListItem -List SitePages -Identity $CurrentItem.Id -Values @{"Modified" = $NowValue} -UpdateType UpdateOverwriteVersion
> Set-PnPPage -Identity $CurrentItem.FieldValues.FileLeafRef -Publish
> ```
> 
> This is how it looks after: ![image](https://github.com/user-attachments/assets/be3bf511-0117-4fa8-ba56-0d5c429b5b9a)

Similar to what @tarjeieo mentions, we face the same issue after "silently" updating som hidden metadata and re-publishing the page. 

$Item = Get-PnPListItem -List SitePages -Id 634
Set-PnPListItem -List SitePages -Identity $Item.Id -Values @{"Title" = "Some random value"}
Set-PnPPage -Identity $Item.FieldValues.FileLeafRef -Publish

From what I can see, the issue relates to operation(s) performed by the Page.Save() function/action (ClientSidePage in PnP.Core), as this is called whenever Set-PnPPage is called, even if you're only intend to publish the page. 

When trying to directly Publish the page by calling $page.Publish(), without using Set-PnPPage -Publish, the page's design/layout persists (as it should). 

I noticed that there is a reported issue in the PnP.Core-repo, [https://github.com/pnp/pnpcore/issues/1614](url) , which relates to somewhat the same issue, only for SaveAsTemplateAsync().

**Comment by gautamdsheth** [comment]
Is this still an issue ? Can anyone check this and let us know , maybe after updating to the latest version 3.4.0 or later nightly builds ? There have been quite a few changes , maybe it is already fixed ?
