### ISSUE TITLE
[BUG] Remove-PnPTermLabel does not honor -Confirm:$false

### ISSUE THREAD

**Issue by 2Who** [pnp/powershell#5018]
### Reporting an Issue
Remove-PnPTermLabel does not honor -Confirm:$false

### Expected behavior 
No prompt for confirmation when -Confirm:$false is set

### Actual behavior 
When calling Remove-PnPTermLabel with -Confirm:$false it still prompts for confirmation.
Delete label Microsoft.SharePoint.Client.Taxonomy.Label for language xxxx from Term xxxx with id xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx

### Steps to reproduce behavior
Remove-PnPTermLabel -Label $myLabel.Value -Term $myTerm-Lcid $myLcid -Confirm:$false

### What is the version of the Cmdlet module you are running?
3.1.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by reshmee011** [comment]
I have create PR #5023 to add a Force parameter to skip confirmation. There is no confirm parameter in the remove cmdlet.

**Comment by gautamdsheth** [comment]
hey @2Who , this has been fixed with the addition of confirm parameter. It is available with tomorrow's nightly as well as next major version when we release it.

**Comment by gruering** [comment]
It appears that this fix did not make it into the current release. Version 3.1.0 still lists Confirm as valid parameter. The confirmation still cannot be suppressed with confirm parameter. Force is not recognized as a parameter.
Do you know when it will be added?
