### ISSUE TITLE
[BUG] PNP-SetListItem - Update Person Field with Multiple People

### ISSUE THREAD

**Issue by abjfdi** [pnp/powershell#605]
Issue

### Expected behavior 
When I use this commandlet with the -Values attribute having multiple email address on either a SP List or a Document Library, when I visited the List/Library I see all inputted Users in the Column.

### Actual behavior 
Commandlet works with SP List. I see all inputted Users in the column.
Commandlet does not work with Document Library. I see 1 inputted user in the column.

### Steps to reproduce behavior
1. Create a List with a Person column and enable the option Allow Multiple Values.
2. Create a Document Library with a Person column and enable the option Allow Multiple Values.
3. Add dummy content to both the List & Document Library
4. Run the below commands, changed to match your environment
```powershell
Set-PnPListItem -List "TestList" -Identity 1 -Values @{PersonColumn=@("user1@contoso.onmicrosoft.com", "user2@contoso.onmicrosoft.com")}

Set-PnPListItem -List "TestDocumentLibrary" -Identity 1 -Values @{PersonColumn=@("user1@contoso.onmicrosoft.com", "user2@contoso.onmicrosoft.com")}
```

### What is the version of the Cmdlet module you are running?
1.3.0, 1.4.0 & 1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

### Notes
On a document library you will see the below warning when you run through the reproduction steps and open "List Settings">"Column"

![image](https://user-images.githubusercontent.com/78413111/115590875-6154b680-a2c9-11eb-8858-ad5e824eb746.png)

### Workaround
Use the [validateUpdateListItem](https://techcommunity.microsoft.com/t5/microsoft-sharepoint-blog/update-file-metadata-with-rest-api-using-validateupdatelistitem/ba-p/1365682) REST API through the Invoke-PnPRestMethod commandlet.

**Comment by veronicageek** [comment]
That's right @abjfdi - I can reproduce the issue (and I was on 1.5.16-nightly)

@gautamdsheth / @erwinvanhunen:
Works on a list but not a library. Only the first name is updated, but the others are not. Even using any of the 3 options for the `-UpdateType` didn't work.

**Comment by gautamdsheth** [comment]
@veronicageek / @abjfdi  - Looks like it is fixed. Can you check with the latest nightly build ? I tested it in list and doc lib both and it works

**Comment by veronicageek** [comment]
@gautamdsheth - Tried with `1.5.36-nightly` but the issue is still there

**Comment by gautamdsheth** [comment]
@veronicageek - I can't reproduce it unfortunately. Tested it again with both list and doc lib and it works. Made auth using PnP Management Shell.

**Comment by veronicageek** [comment]
@abjfdi - Can you please try and feedback. Thanks

**Comment by abjfdi** [comment]
@veronicageek Still doesn't work for me on 1.5.52-nightly.

**Comment by veronicageek** [comment]
Update: Tested with `1.7.39` and still an issue.

**Comment by KoenZomers** [comment]
I can reproduce this issue. The issue lies on the server side I'm afraid. Nothing we can do about it from PnP PowerShell. @abjfdi are you able to open a support ticket with Microsoft Support on this? You may reference my name for the support engineer to contact for further information.

**Comment by abjfdi** [comment]
Can't reproduce this on 1.7.0. Did not raise a support ticket. I tried to reproduce the issue before submitting.  Can @veronicageek or @KoenZomers reproduce this again? Just to rule out tenancy issues.

**Comment by KoenZomers** [comment]
@abjfdi do you mean to say it works for you now on 1.7.0? I tested it with the latest dev branch code and could reproduce the issue and could lead it down to the SharePoint Online API side being the problem as the request sent to it looks perfectly legitimate and not any different from a call towards a SharePoint list with a multi person column where it does work. Also the code in this cmdlet on the PnP PowerShell side hasn't been touched since a long time, so 1.7.0 could not have made a change in this, unless of course the server side happens to have been patched since my testing 3 days ago, which I would deem unlikely.

**Comment by abjfdi** [comment]
@KoenZomers I'm not sure what changed or when, all I can say is that I no longer can reproduce. I'm guessing that the server side has changed and is being rolled out by the SP team and that takes time to rollout completely. So if my guess is correct some tenants have the issue while others do not. But this is all a guess.

**Comment by KoenZomers** [comment]
Interesting. Let me try it again here then as well. Perhaps it does happen to be a coincidental update on the server side during the past weekend then.

**Comment by KoenZomers** [comment]
On my main tenant it still doesn't work. On a new tenant I found it to work sometimes. It really depends on who I'm trying to add in the Person column. For some combinations of people it may add more than one, for other combinations it only adds one. Pretty random. I also can't find any work being done or having been done on this recently in the work items. Let me ask around some.

**Comment by KoenZomers** [comment]
Can't find any work being done on the engineering side on this. If anyone is still experiencing this issue, please open a support ticket with Microsoft on this, referencing this GitHub thread and mentioning my name so we can get some movement on this.

**Comment by Markus-Hanisch** [comment]
@KoenZomers 
Recently, I had a project where I wanted to use the Set-PnPListItem cmdlet to update a Person or Group Column with multiple values using the IDs of the corresponding PnPUser.

The cmdlet worked whenever I hardcoded multiple values (IDs) to update a single item.
Whenever I used a foreach loop to Import values from CSV or array, it only set the first value of the Collection of values.
Tried several ways and after couple of hours ended up with copy pasting the multi value collections in the quick edit Mode in the GUI.... very poor user experience and very frustrating.
