### ISSUE TITLE
[BUG] Get-PnPAzureADUser: -Select parameter ignored

### ISSUE THREAD

**Issue by sergeyz7** [pnp/powershell#649]
### Reporting an Issue or Missing Feature
The _-Select_ parameter of the _Get-PnPAzureADUser_ is being ignored.

### Expected behavior 
As per the [Official Graph Documentation](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#optional-query-parameters) and the [PnP Documentation](https://pnp.github.io/powershell/cmdlets/Get-PnPAADUser.html#-select), providing a value for the _select_ query parameter should result in an alternative set of object properties being returned.

### Actual behavior 
The cmdlet returns the same default set of properties:
![Get-PnPAzureADUser_bug1](https://user-images.githubusercontent.com/45974226/117012273-ad9af000-ace6-11eb-89b1-4850dcf90771.png)

### Steps to reproduce behavior
Looking at the associated traffic exchange with graph.microsoft.com reveals 2 underlying issues:

1. The names of properties specified in the value for the _-Select_ parameter get **appended** to the default set, instead of being presented exclusively:
![Get-PnPAzureADUser_bug2](https://user-images.githubusercontent.com/45974226/117012720-2437ed80-ace7-11eb-956d-c1ece5772e99.png)

2. The returned payload **does** actually contain name-value pairs for the requested properties, but those seem to be ignored in the cmdlet output:
![Get-PnPAzureADUser_bug3](https://user-images.githubusercontent.com/45974226/117013089-74af4b00-ace7-11eb-98f1-ea1a6b56dce8.png)

### What is the version of the Cmdlet module you are running?
1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [x] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by sergeyz7** [comment]
Bump

**Comment by veronicageek** [comment]
@sergeyz7 - I can indeed reproduce the issue. Meanwhile, you can use the `Select-Object` as a workaround while we look into it.

![image](https://user-images.githubusercontent.com/25181757/119403357-19fd8380-bcd6-11eb-9312-902cb9ff54d6.png)

**Comment by mbuergi** [comment]
Is there an update to this issue?
Using Select-Object is not a viable workaround, as this works only for properties that are returned by default by "Get-PnPAzureADUser" 

It is not possible to retrieve other AAD User Properties like "Company", "City" or "Extensionattribute1" etc.

**Comment by KoenZomers** [comment]
This should be resolved in the nightly build of PnP PowerShell that happens the night after this PR in PnP Framework gets merged:
https://github.com/pnp/pnpframework/pull/460

Closing this issue for now assuming that resolves it. If it turns out it didn't, feel free to reopen this issue.

**Comment by KoenZomers** [comment]
PR has been merged. You can test this with the latest prerelease of PnP PowerShell starting tomorrow, September 24, 2021.

**Comment by RobinDijkstra** [comment]
It looks like this bug is not solved completely. In the commit that @KoenZomers realised, the properties that are passed with the -Select parameter are added to user.AdditionalProperties which only resolves problem 2 of the original issue. Problem 1 however isn't solved because all the default properties are still returned, even when the -select parameter is passed. The documentation states:

**-Select**
_Allows providing an array with the property names of specific properties to return. If not provided, the default properties will be returned._

Also example 5 of the documentation illustrates this behavior: "Retrieves only the DisplayName and extensionAttribute1 properties..."

However, I realize that correcting this behavior as documented is a breaking change. So perhaps the documentation of -Select needs to be modified to describe the current behavior (additional properties). To solve the issue, an extra parameter could be introduced to state that we don't want to receive all default properties, i.e. -IgnoreDefaultProperties.

For performance reasons, only the properties that are asked for should be retrieved from the Graph API.

**Comment by KoenZomers** [comment]
Good idea @RobinDijkstra! I've added it as you suggested through https://github.com/pnp/powershell/pull/1575. You're welcome next time to add it yourself and file a PR, too :)
